version: "3.3"
networks:
  rest-sample:
    driver: bridge
volumes:
  rest-sample-mysql-volume:
    driver: local
services:
  rest-sample-mysql:
    container_name: rest-sample-mysql
    build:
      context: ./docker/mysql
    networks:
      - rest-sample
    dns:
      - 8.8.8.8
      - 8.8.4.4
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "2"
    restart: "no"
    ports:
      - 53306:3306
    volumes:
      - rest-sample-mysql-volume:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --default-authentication-plugin=mysql_native_password
    environment:
      TERM: linux
      LANG: "C.UTF-8"
      MYSQL_ROOT_PASSWORD: ${DB_PASS:-laravel}
      MYSQL_DATABASE: ${DB_NAME:-rest_sample}
      LOG_ROTATION_DAY: 7
  rest-sample-api:
    build:
      context: ./docker/rest-sample-api
    container_name: rest-sample-api
    depends_on:
      - rest-sample-mysql
    networks:
      - rest-sample
    ports:
      - "5080:80"
      - "55173:55173"
    volumes:
      - ./submodules/rest-sample-api:/var/www/rest-sample-api
    environment:
      APP_NAME: "rest-sample-api"
      APP_ENV: local
      APP_KEY: "base64:qcPfU/VDf6uuipgg/y1cI8dwGEM9BUYFoFU3qrpLEeE="
      APP_DEBUG: "true"
      APP_URL: ${API_PUBLIC_URL:-http://rest-sample-api:80/api}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:5081}
      ACCESS_CONTROL_ALLOW_ORIGIN: ${FRONTEND_URL:-http://localhost:5081}
      HELP_MAIL_ADDRESS: info@localhost
      DB_CONNECTION: mysql
      DB_HOST: rest-sample-mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_NAME:-rest_sample}
      DB_USERNAME: root
      DB_PASSWORD: ${DB_PASS:-laravel}
      MAIL_MAILER: ${MAIL_MAILER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
      MAIL_FROM_ADDRESS: "api@rest-sample"
      MAIL_FROM_NAME: "rest-sample-api"
      BROADCAST_DRIVER: "pusher"
      PUSHER_APP_ID: ${PUSHER_APP_ID}
      PUSHER_APP_KEY: ${PUSHER_APP_KEY}
      PUSHER_APP_SECRET: ${PUSHER_APP_SECRET}
      PUSHER_APP_CLUSTER: ${PUSHER_APP_CLUSTER}
  rest-sample-frontend:
    build:
      context: ./docker/rest-sample-frontend
    container_name: rest-sample-frontend
    networks:
      - rest-sample
    ports:
      - "5081:3000"
    volumes:
      - ./submodules/rest-sample-frontend:/app
    environment:
      HOST: ${HOST:-localhost}
      TITLE: "Custom URL Scheme Sample"
      HOME_URL: ${FRONTEND_URL:-http://localhost:5081}
      API_URL: ${API_PRIVATE_URL:-http://rest-sample-api:80/api}
      API_URL_BROWSER: ${API_PUBLIC_URL:-http://localhost:5080/api}
      ACCESS_KEY_ID: "rest-sample-dummy"
      SENTRY_DSN: ${SENTRY_DSN}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
    command: npm run dev